
INFO6105 Instructor: Dr. Handan Liu

Homework 1  

Name: Dhruvil Shah

NUID: 001873473

Grading: total 100 points.


In [2]:
import numpy as np
np.random.seed(0)
a = np.array([1,2,3])
a

array([1, 2, 3])

In [10]:
x=[1,2]
b = np.array(x)
b

array([1, 2])

In [13]:
array3 = np.ones((3,2),dtype=float)
array3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
array4 = np.eye(3, dtype=int)
array4

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [15]:
array5 = np.full((2, 5), 6, dtype=np.uint)
array5

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

In [29]:
array6 = np.arange(start=2, stop=102, step=2)
array6

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [27]:
array7=np.zeros(10)
print(array7)
array8=np.ones(10)*5
print(array8)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [28]:
np.random.seed(10)
x = np.random.random((3,3,3))
print(x)

[[[0.77132064 0.02075195 0.63364823]
  [0.74880388 0.49850701 0.22479665]
  [0.19806286 0.76053071 0.16911084]]

 [[0.08833981 0.68535982 0.95339335]
  [0.00394827 0.51219226 0.81262096]
  [0.61252607 0.72175532 0.29187607]]

 [[0.91777412 0.71457578 0.54254437]
  [0.14217005 0.37334076 0.67413362]
  [0.44183317 0.43401399 0.61776698]]]


In [29]:
m= np.arange(10,22).reshape((3, 4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [32]:
ar9 = np.zeros((4, 4))
ar9[::2, 1::2] = 1
ar9[1::2, ::2] = 1
print(ar9)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [6]:
#1
np.random.seed(10)


print ("first Number ", np.random.randint(25,50))
np.random.seed(10)
print ("Second Number ", np.random.randint(25,50))
np.random.seed(10)
print ("Third Number ", np.random.randint(25,50))

first Number  34
Second Number  34
Third Number  34


In [111]:
#2
np.random.seed(10)  
x2 = np.random.random_sample(size=(3, 2))  # Two-dimensional array
x2

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665]])

In [132]:
#3
np.random.seed(10)  
x2 = np.random.randint(0,4,size=(3, 2))
x2

array([[1, 1],
       [0, 3],
       [0, 1]])

In [153]:
x = [1,2,3,4,5,6,7,8,9]
np.split(x,[4,6,9])

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9]), array([], dtype=int32)]

In [163]:
arr = np.arange(16).reshape((4, 4))
print("Original array:",arr)
print("After splitting along second axis:")
print(np.hsplit(arr, [2, 6]))

Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting along second axis:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


In [228]:
givenArr = np.array([[5,10,15],[20,25,30],[35,40,45]])

#1 Slicing to get the sub-array [[10,15],[25,30]]

print(givenArr[0:2,1:3])


#2 Getting individual element value "20"
#Method1
print(givenArr.item(3))

#Method2

print(np.take(givenArr,3))


[[10 15]
 [25 30]]
20
20


In [242]:
x = np.array([[ 1, 2, 3],
 [ 4, 5, 6]])

y= np.array([[7, 8, 9],[10, 11, 12]])

result= np.hstack((x,y))
print(result)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [244]:
arr4 = np.array([ 3,  6,  9,  25, 10,  8])
print(arr4[1:])


[ 6  9 25 10  8]


In [245]:
arr4 = np.array([ 3,  6,  9,  25, 10,  8])
print(arr4[:-1])

[ 3  6  9 25 10]


In [246]:
arr4 = np.array([ 3,  6,  9,  25, 10,  8])
print(arr4[::2])

[ 3  9 10]


In [247]:
arr4 = np.array([ 3,  6,  9,  25, 10,  8])
print(arr4[1::2])

[ 6 25  8]


In [248]:
arr4 = np.array([ 3,  6,  9,  25, 10,  8])
print(arr4[::-1])

[ 8 10 25  9  6  3]


In [254]:
a = np.random.randint(0, 31, (8,4))
print(a)

[[20 18 16 14]
 [19 15 19 17]
 [18 21 25 14]
 [16 10 17  0]
 [17  9 16  9]
 [26 12 18 30]
 [17 17 28 16]
 [ 0  5  9  0]]


In [258]:
a[0,2]=0
print(a)

[[20 18  0 14]
 [19 15 19 17]
 [18 21 25 14]
 [16 10 17  0]
 [17  9 16  9]
 [26 12 18 30]
 [17 17 28 16]
 [ 0  5  9  0]]


In [263]:
print(a[:,1:2])

[[18]
 [15]
 [21]
 [10]
 [ 9]
 [12]
 [17]
 [ 5]]


In [264]:
print(a[:3,:3])

[[20 18  0]
 [19 15 19]
 [18 21 25]]


In [266]:
arr = np.random.randn(1000)
print("Average of the array elements:")
mean = arr.mean()
print(mean)
print("Standard deviation of the array elements:")
stand = arr.std()
print(stand)
print("Variance of the array elements:")
var = arr.var()
print(var)

Average of the array elements:
-0.012342548866172276
Standard deviation of the array elements:
0.9804013665426712
Variance of the array elements:
0.9611868395187371


In [11]:
from numpy import array, newaxis
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

print('shape of a',a.shape)
print('shape of b',b.shape)
print((a+b).shape)
#According to Rule 3, the dimensions of both the arrays disagrees an error is generated



shape of a (4,)
shape of b (3,)


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [13]:
#Using newaxis
print(a[:,newaxis] + b)



[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [8]:
#Using Rule1 of reshape
x = np.arange(4).reshape(4,1)
y = np.ones(5)

x+y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [10]:
#Using newAxis
from numpy import array, newaxis
x = np.arange(4)
print("X:",x)
y = np.ones(5)
print("Y:",y)
#print(x+y)
print(x[:,newaxis] + y)

X: [0 1 2 3]
Y: [1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [290]:
#Using Broadcasting
x = np.arange(1,7)
y=np.arange(1,7)
print(x)
print(y)
print(x[:,newaxis] * y)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [54]:
#Using for loops
#rows, cols = (6, 6) 
#p = [[0 for i in range(cols)] for j in range(rows)] 

p = np.zeros((6,6))

for i in range(0,6):
    for j in range(0,6):
        p[i][j]=(i+1)*(j+1)
        
p

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 2.,  4.,  6.,  8., 10., 12.],
       [ 3.,  6.,  9., 12., 15., 18.],
       [ 4.,  8., 12., 16., 20., 24.],
       [ 5., 10., 15., 20., 25., 30.],
       [ 6., 12., 18., 24., 30., 36.]])

In [41]:
#1 Creating array of 10 obeservations.
x = np.random.random((10, 3))
print("Array of (10,3):", x)

#2 computing mean
x_mean = x.mean(0)
print("Compute the mean:")
print(x_mean)

#3 Center of arr by subtracting mean
x_centered = x - x_mean
print("Center the Array by subtracting the mean:")
print(x_centered)

#4 Double check 
print("Double-check the correctness :", x_centered.mean(0))


Array of (10,3): [[0.81872157 0.16034803 0.66069534]
 [0.17663505 0.48419866 0.71355456]
 [0.48120129 0.14075845 0.73078739]
 [0.8122959  0.72382052 0.6717323 ]
 [0.26411314 0.27607332 0.84169919]
 [0.51575165 0.82808948 0.62973071]
 [0.54188732 0.82561156 0.6778163 ]
 [0.69427663 0.2191785  0.9003574 ]
 [0.13161621 0.12625124 0.15319693]
 [0.34380989 0.00846691 0.13208193]]
Compute the mean:
[0.47803086 0.37927967 0.6111652 ]
Center the Array by subtracting the mean:
[[ 0.34069071 -0.21893164  0.04953014]
 [-0.30139582  0.10491899  0.10238935]
 [ 0.00317042 -0.23852122  0.11962218]
 [ 0.33426503  0.34454085  0.06056709]
 [-0.21391772 -0.10320634  0.23053399]
 [ 0.03772079  0.44880981  0.01856551]
 [ 0.06385646  0.44633189  0.0666511 ]
 [ 0.21624576 -0.16010116  0.28919219]
 [-0.34641466 -0.25302843 -0.45796827]
 [-0.13422097 -0.37081276 -0.47908328]]
Double-check the correctness : [ 3.33066907e-17  2.22044605e-17 -5.55111512e-17]
